// <auto-generated />
namespace CarFuel.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addusersandcardowner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addusersandcardowner));
        
        string IMigrationMetadata.Id
        {
            get { return "201608310643443_Add users and card owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
